baseURL = "https://joshua0128.github.io/"
languageCode = "en"
title = "Wei's Blog"
theme = "beautifulhugo"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"

# for high light
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
# disqusShortname = "YOUR_DISQUS_SHORT_NAME"
# googleAnalytics = "UA-XXXXXXXXX-X"
paginate = 4


[Params]
  description = ""
  subtitle = "記不住的東西都放在這"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  comments = true
  #dateFormat = "January 28, 2021"
  #readingTime = true
  #wordCount = true
  useHLJS = true
  showRelatedPosts = true
  socialShare = true
  delayDisqus = true


[Author]
  name = "Wei"
  website = "https://joshua0128.github.io"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
