baseURL = "https://joshua0128.github.io/"
languageCode = "en-US"
title = "Eureka"
theme = "hago"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
# disqusShortname = "YOUR_DISQUS_SHORT_NAME"
# googleAnalytics = "UA-XXXXXXXXX-X"
paginate = 4


[Params]
  description = "note from wei"
  subtitle = "blog"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  comments = true

[Category]

[Author]
  name = "joshua0128"
  website = "https://joshua0128.github.io"
